### ISSUE TITLE
'dpkg --status' returns 0 for packages that were removed

### ISSUE THREAD

**Issue by mgedmin** [cederberg/ansible-bootstrap-debian#2]
I noticed you're using
```
if dpkg --status $PKG > /dev/null 2>&1 ; then
```
to check if a package is installed.  This will not work if the package was explicitly removed:

```
$ sudo apt-get remove aptitude
$ dpkg --status aptitude >/dev/null 2>&1 ; echo $?
0
$ dpkg --status aptitude | grep ^Status
Status: deinstall ok config-files
```

I suggest changing the check to something like
```
if ! [ "$(dpkg-query -W --showformat='${Status}' $PKG)" = "install ok installed" ]; then
```
instead.

**Comment by cederberg** [comment]
Thanks! Wasn't aware of this strange anti-scripting behavior in the Debian package tools.

After researching alternative solutions for a while, I think the suggested string comparison is actually the best. Now committed.
